# Generated by Django 6.0 on 2025-12-05 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_remove_profile_website_alter_experience_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='link',
            new_name='demo',
        ),
        migrations.AddField(
            model_name='project',
            name='github',
            field=models.URLField(blank=True),
        ),
    ]
