# Generated by Django 6.0 on 2025-12-05 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_rename_link_project_demo_project_github'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hero_button_primary',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='hero_button_primary_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='hero_button_secondary',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='hero_button_secondary_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='hero_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='hero_heading',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='hero_subheading',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
