# Generated by Django 6.0 on 2025-12-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_profile_hero_button_primary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hero_highlight_1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='hero_highlight_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='hero_highlight_3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='hero_typing_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='stat_title_1',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='profile',
            name='stat_title_2',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='profile',
            name='stat_title_3',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='profile',
            name='stat_value_1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='stat_value_2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='stat_value_3',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
