# Generated by Django 6.0 on 2025-12-06 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_certificate_education_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='year',
        ),
        migrations.AddField(
            model_name='certificate',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.profile'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='issuer',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
