# Generated by Django 6.0 on 2025-12-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stat_title_4',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='profile',
            name='stat_value_4',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
