# Generated by Django 6.0 on 2025-12-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_profile_stat_title_4_profile_stat_value_4'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='skill_group',
            field=models.CharField(blank=True, choices=[('programming', 'Programming & Scripting'), ('testing_tools', 'Testing Tools'), ('testing_methods', 'Testing Methodologies'), ('systems_platforms', 'Systems & Platforms'), ('domain_expertise', 'Domain Expertise'), ('additional', 'Additional'), ('soft_general', 'Soft Skills')], max_length=50),
        ),
    ]
