# Generated by Django 6.0 on 2025-12-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_skill_skill_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
