# Generated by Django 6.0 on 2025-12-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0013_skill_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='focus_later',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='profile',
            name='focus_next',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='profile',
            name='focus_now',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
