# Generated by Django 6.0 on 2025-12-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0014_profile_focus_later_profile_focus_next_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='resume_pdf',
            field=models.FileField(blank=True, help_text='Upload your PDF resume', null=True, upload_to='resumes/'),
        ),
    ]
