# Generated by Django 6.0 on 2025-12-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0015_profile_resume_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('anime', 'Anime'), ('movie', 'Movie'), ('band', 'Band')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='fun_items/')),
            ],
        ),
    ]
