# Generated by Django 6.0 on 2025-12-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0016_favoriteitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='favoriteitem',
            name='year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
